### ISSUE TITLE
Xcode 12.5 does not compile

### ISSUE THREAD

**Issue by si-hartmann** [fritzlabs/swift-framework#107]
**Describe the bug**
Xcode does not compile with Xcode 12.5 using SPM due to the pre build framework.

One of the error: Failed to build module 'FritzManagedModel' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)'

**Your Environment:**
 - Xcode Version: 12.5
 - Swift or Obj-C: Swift
 - Swift version: 5.4

**Comment by jamesonthecrow** [comment]
Fritz 6.1.4 has been released. Please re-open this issue if you have any issues building for Xcode 12.5.
