### ISSUE TITLE
Cant run fritz framework with swift 5.0 compiler 

### ISSUE THREAD

**Issue by GalaevAlexey** [fritzlabs/swift-framework#71]
Getting error:

`module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler`

**Comment by ghop02** [comment]
Hi! Sorry about that, we have a branch (which is a little bit outdated) 
https://github.com/fritzlabs/swift-framework/tree/swift-5.0
that should be compatible.  

```
pod 'Fritz': :git => 'https://github.com/fritzlabs/swift-framework.git', :branch => 'swift-5.0'
```
should work.

**Comment by GalaevAlexey** [comment]
Thank you for fast answer, i will check.

**Comment by Olshansk** [comment]
> pod 'Fritz', :git => 'https://github.com/fritzlabs/swift-framework.git', :branch => 'swift-5.0'

Minor syntax fix.

**Comment by douglundin** [comment]
Any luck/status on getting the heartbeat app updated for Swift 5.0?

**Comment by ghop02** [comment]
Ah hi! Yes, if you install 3.2.0-beta.2 you should be good to go.  Going to promote it from beta later today.

**Comment by douglundin** [comment]
Is the Cocoapods distro going to be updated and when do you anticipate that will happen?

**Comment by ghop02** [comment]
Yup, running `pod trunk push` as we speak!

**Comment by ghop02** [comment]
Alright, https://github.com/fritzlabs/swift-framework/releases/tag/3.2.0 is out on cocoapods!

Sorry for the delay and thanks for all the input. Don't hesitate to reach out with any issues you find.

**Comment by douglundin** [comment]
Building the heartbeat app results in an error. Use of unresolved identifier 'LinkTableViewCell'. I don't recall seeing it in Swift 4.2.1.

on line         tableView.register(LinkTableViewCell.self, forCellReuseIdentifier: "LinkTableViewCell")

**Comment by ghop02** [comment]
Ah, I just pushed a bunch of fixes. Can you try again on the latest master?

**Comment by douglundin** [comment]
I pulled the latest heartbeat source but am now getting this error:

coremlc: Error: Error reading protobuf spec. validator error: unable to deserialize object
Command CoreMLModelCompile failed with a nonzero exit code

It's using Fritz 3.2.0 - is that the right version to be using?

**Comment by ghop02** [comment]
Yes! that seems like a different error. It might be easiest if we debug in another channel.  Feel free to ping me in the heartbeat slack.

Actually, looks like we've seen this issue before! If that doesn't work, feel free to open up a new issue or comment on that issue in the heartbeat-ios project:
https://github.com/fritzlabs/heartbeat-ios/issues/4
