### ISSUE TITLE
Fritz not working with Xcode 11 beta 

### ISSUE THREAD

**Issue by Shoshin23** [fritzlabs/swift-framework#81]
**Describe the bug**
The Fritz swift framework isn't running on Xcode 11 beta because of the following error: 
`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler.
`
I understand that this something only developers of Fritz can fix right now and would love to have support for this. 

Thanks!

**Your Environment:**
 - Xcode Version: 11 beta 1
 - Swift or Obj-C: Swift
 - Swift version: 5.0.1
 - iOS Version: 13
 - Fritz SDK version: latest

**Comment by genadyo** [comment]
👍🏻

**Comment by ghop02** [comment]
Hi @Shoshin23 and @genadyo , the latest beta version `3.6.0-beta.2` works on Xcode 11 Beta 3! `3.6.0-beta.1` should work on Beta 2.  Sorry for the delay.

**Comment by maxgribov** [comment]
Hi @ghop02 , can you provide instructions how to install 3.6.0-beta.2?

**Comment by maxgribov** [comment]
in Xcode Version 11.0 beta 4 still still not working:
<img width="1200" alt="Screenshot 2019-07-19 at 19 21 36" src="https://user-images.githubusercontent.com/6514571/61550221-97ad3400-aa5a-11e9-9c82-95661361176b.png">
Even if I switch on legacy build system

**Comment by ghop02** [comment]
Ah, I dont' think beta 2 will work on beta 4.  I'll run the build for that now

**Comment by ghop02** [comment]
Hi @maxgribov, 3.6.0-beta.3 should work with Beta 4. Let me know if you have any issues

**Comment by maxgribov** [comment]
@ghop02 `3.6.0-beta.3` builds perfectly in `Xcode 11.0 beta 4`. Thank you!

**Comment by maxgribov** [comment]
Hi @ghop02, could you please run build for Xcode 11 beta 5?

**Comment by ghop02** [comment]
3.6.0-beta.4 is now out and works with Xcode Beta 5

**Comment by PallaviThakare** [comment]
hi @ghop02  I am getting same issue as "Module compiled with Swift 5.1 cannot be imported by the Swift 4.2.1 compiler" on Xcode version 10.1, How can I resolve that?

**Comment by ghop02** [comment]
Hi @PallaviThakare.  The latest versions of Fritz (4.0.1) only support version 10.3+.  Are you planning on upgrading Xcode soon? Also feel free to reach out at help@fritz.ai for more assistance!
