### ISSUE TITLE
iOS 13.2 support

### ISSUE THREAD

**Issue by puria-izady** [fritzlabs/swift-framework#87]
**Describe the bug**
Hi,

that's actually no bug, but I wanted to ask you when there will be official support for iOS 12.2, because right now I get the error in XCode that the framework only supports Swift Compiler 5.1 but not Swift Compiler 5.1.1.

**Your Environment:**
 - Xcode Version 11.2 beta 2 
 - Swift or Obj-C: Swift
 - Swift version: 5.1.1
 - iOS Version: 12.2
 - Fritz SDK version: 4.3.0-beta.2

**Additional context**

**Comment by ghop02** [comment]
Hi, the latest version is built with an updated version of swift, but it may not work on the latest version.  The cocoapods build for 4.3.0-beta.2 will be out shortly, but the frameworks are available on the release section right now

**Comment by puria-izady** [comment]
@ghop02 thanks for your reply. Right now I got it running on iOS 13.2 through XCode 11.1, by tweaking the iOS 13.2 device support of XCode with this:

```
sudo ln -s /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/13.2 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
```
